### ISSUE TITLE
👾 [Bug]: 런칭 전 기타 버그 수정

### ISSUE THREAD

**Issue by CosmicLatte009** [oxxun21/Code-Catcher-FE#100]
## Description
런칭 전 디자인, createdDate 등 수정 

## To-do
- [x] 문제 선택 카드 제목 정렬 수정
- [x] 지난 테스트 내역, 북마크 페이지 createdDate 날짜 수정
- [x] 월간 달성률 화살표 fix
