### ISSUE TITLE
🛠️ [Feature]: Google Tanslate 번역위젯

### ISSUE THREAD

**Issue by CosmicLatte009** [oxxun21/Code-Catcher-FE#106]
## Description
구글 번역 위젯 

## To-do
- [x] 번역위젯 컴포넌트 헤더에 달기
- [x] 1 -> one 문제 수정
- [x] 패딩에 잡아먹히는 영문 수정
- [x] 이미지 영문 수정
- [x] 번역 토글 시  배포단에서 쿠키 두번 중복되는 문제
