### ISSUE TITLE
👾 [Bug]: Header UI 수정 

### ISSUE THREAD

**Issue by CosmicLatte009** [oxxun21/Code-Catcher-FE#12]
## Description
Header가 import되지 않고 수정

## To-do
- [x] index.ts에서 Header와 SplashCarousel import 다시 해오기 
- [x] Header의 height를 padding으로 대체, max-width를 width로 대체
- [x] 헤더 컴포넌트에서 로그인 상태 여부에 따라 로그아웃/마이페이지로 전환.

## ETC
기타사항
