### ISSUE TITLE
🛠️ [Feature]: 코딩테스트 문제 풀이 페이지 기능 추가

### ISSUE THREAD

**Issue by oxxun21** [oxxun21/Code-Catcher-FE#16]
## Description
코딩테스트 문제 풀이 페이지 기능 추가

## To-do
- [x] 라우트 `:문제 id` 로 수정
- [x] 문제 불러오기
- [x] 제출 기능
- [x] 테스트 케이스 기능
- [x] 채점 및 결과 표시
- [x] 문제 정답/오답에 따른 모달 구현
