### ISSUE TITLE
💅 [Style]: 코딩테스트 문제 풀이 화면 구현

### ISSUE THREAD

**Issue by oxxun21** [oxxun21/Code-Catcher-FE#2]
## Description
코딩테스트 문제 풀이 화면 구현

## To-do
- [x] 문제 설명 UI
- [x] 코드 작성 UI
- [x] 실행 결과 UI
- [x] 언어 선택 옵션
- [x] gutter 구현

## ETC
언어 선택 기능은 옵션만 만들어두고 기능은 자바만 우선 진행하겠습니다

**Comment by CosmicLatte009** [comment]
확인했습니당. 첫 PR 고생하셨어여~
