### ISSUE TITLE
💅 [Style]: 스플래쉬 화면 UI 구현

### ISSUE THREAD

**Issue by CosmicLatte009** [oxxun21/Code-Catcher-FE#4]
## Description
로그인하기 전 스플래쉬 화면 UI 구현. 

## To-do
- [x] 카카오 소셜 로그인 버튼 css
- [x] 슬라이드 컴포넌트 css
- [x] 헤더 컴포넌트 css

## ETC
슬라이드 우측 이미지 제외하고 우선 레이아웃 맞춰서만 구현할게요.
