### ISSUE TITLE
🛠️ [Feature]: 마이페이지에 필요한 리스트 api 요청 및 유저 정보 업데이트

### ISSUE THREAD

**Issue by CosmicLatte009** [oxxun21/Code-Catcher-FE#55]
## Description
마이페이지에 필요한 리스트 api 요청 및 유저 정보 업데이트

## To-do
- [x] react-calender 라이브러리 스타일링 및 필요한 속성 수정
- [x] 월간 달성률 정보 GET
- [x] 유저 정보 GET 및 useUserStore 업데이트 로직 추가
- [x] 북마크 및 지난 테스트 리스트 (마이페이지용 4개) GET
