### ISSUE TITLE
🛠️ [Feature]: 코드 비교 페이지 기능

### ISSUE THREAD

**Issue by oxxun21** [oxxun21/Code-Catcher-FE#58]
## Description
코드 비교 페이지 기능 및 API 연결

## To-do
- [x] 내 코드, AI 코드 출력
- [x] AI 피드백 출력

## ETC
- [ ] AI 섹션 gutter 수정
- [ ] API 호출 error 처리
