### ISSUE TITLE
🛠️ [Feature]: 카카오 OAuth 로그인 요청 구현

### ISSUE THREAD

**Issue by CosmicLatte009** [oxxun21/Code-Catcher-FE#7]
## Description
카카오 OAuth 로그인 요청 구현.

## To-do
- [x] 카카오 rest api 키, redirect uri 환경변수에 저장
- [x] KakaoRedirection 페이지 생성
- [x] KakaoRedirection 페이지로 이동하며 카카오가 주는 인가 코드 받아오도록 카카오 로그인 버튼에 이벤트 핸들러 연결
- [x] 백엔드에 인가코드 보낸 후 response 받아와지는지 테스트
- [x] response에 담긴 token 저장하기 (-> 우선은 localStorage에. 차후 상태관리 도입 필요)
- [x] 백엔드로부터 기타 유저 정보 (유저 id, 닉네임) 받아와서 상태에 저장하기
